# Generated by Django 4.2.7 on 2025-06-14 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=80, verbose_name='Nome do Projeto')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('shift', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10, verbose_name='Turno')),
                ('start_time', models.TimeField(verbose_name='Horário de Início')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=10, verbose_name='Status')),
                ('enrollment_code', models.SlugField(editable=False, unique=True, verbose_name='Código de Matrícula')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Matrícula')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_enrollments', to='members.beneficiary')),
            ],
            options={
                'verbose_name': 'Matrícula em Projeto',
                'verbose_name_plural': 'Matrículas em Projetos',
                'ordering': ['project_name', 'weekday', 'start_time'],
            },
        ),
    ]
