# Generated by Django 4.2.13 on 2025-07-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Projeto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('coordinator', models.CharField(max_length=100, verbose_name='Coordenador')),
                ('location', models.CharField(max_length=200, verbose_name='Local')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('PAUSADO', 'Pausado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('max_participants', models.PositiveIntegerField(default=30, verbose_name='Máximo de Participantes')),
                ('objectives', models.TextField(verbose_name='Objetivos do Projeto')),
                ('target_audience', models.CharField(max_length=200, verbose_name='Público Alvo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('shift', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10, verbose_name='Turno')),
                ('start_time', models.TimeField(verbose_name='Horário de Início')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=10, verbose_name='Status')),
                ('enrollment_code', models.SlugField(editable=False, unique=True, verbose_name='Código de Matrícula')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Matrícula')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_enrollments', to='members.beneficiary')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Matrícula em Projeto',
                'verbose_name_plural': 'Matrículas em Projetos',
                'ordering': ['project__name', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='Data da Sessão')),
                ('start_time', models.TimeField(verbose_name='Horário de Início')),
                ('end_time', models.TimeField(verbose_name='Horário de Término')),
                ('topic', models.CharField(max_length=200, verbose_name='Tópico/Tema')),
                ('description', models.TextField(blank=True, verbose_name='Descrição da Sessão')),
                ('facilitator', models.CharField(max_length=100, verbose_name='Facilitador')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('materials_needed', models.TextField(blank=True, verbose_name='Materiais Necessários')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Sessão Obrigatória')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Sessão do Projeto',
                'verbose_name_plural': 'Sessões do Projeto',
                'ordering': ['session_date', 'start_time'],
                'unique_together': {('project', 'session_date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Recurso')),
                ('resource_type', models.CharField(choices=[('material', 'Material'), ('equipamento', 'Equipamento'), ('local', 'Local'), ('humano', 'Recurso Humano'), ('financeiro', 'Financeiro')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='Fornecedor')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Recurso do Projeto',
                'verbose_name_plural': 'Recursos do Projeto',
                'ordering': ['project__name', 'resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('FINAL', 'Final')], max_length=20, verbose_name='Tipo de Relatório')),
                ('period_start', models.DateField(verbose_name='Início do Período')),
                ('period_end', models.DateField(verbose_name='Fim do Período')),
                ('summary', models.TextField(verbose_name='Resumo Executivo')),
                ('achievements', models.TextField(verbose_name='Conquistas')),
                ('challenges', models.TextField(verbose_name='Desafios')),
                ('metrics', models.JSONField(default=dict, verbose_name='Métricas')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendações')),
                ('created_by', models.CharField(max_length=100, verbose_name='Criado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Relatório do Projeto',
                'verbose_name_plural': 'Relatórios do Projeto',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('target_date', models.DateField(verbose_name='Data Prevista')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('responsible', models.CharField(max_length=100, verbose_name='Responsável')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Marco do Projeto',
                'verbose_name_plural': 'Marcos do Projeto',
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Avaliação (1-5)')),
                ('content_quality', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Qualidade do Conteúdo (1-5)')),
                ('facilitator_rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Avaliação do Facilitador (1-5)')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('suggestions', models.TextField(blank=True, verbose_name='Sugestões')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Recomendaria para outros')),
                ('evaluation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='projects.projectenrollment', verbose_name='Inscrição')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='projects.projectsession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Avaliação de Projeto',
                'verbose_name_plural': 'Avaliações de Projetos',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MATERIAL', 'Material'), ('EQUIPAMENTO', 'Equipamento'), ('RECURSO_HUMANO', 'Recurso Humano'), ('TRANSPORTE', 'Transporte'), ('ALIMENTACAO', 'Alimentação'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Planejado')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Real')),
                ('date_planned', models.DateField(verbose_name='Data Planejada')),
                ('date_actual', models.DateField(blank=True, null=True, verbose_name='Data Real')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Item do Orçamento',
                'verbose_name_plural': 'Itens do Orçamento',
                'ordering': ['date_planned'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False, verbose_name='Presente')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Chegada')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Saída')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='projects.projectenrollment', verbose_name='Inscrição')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='projects.projectsession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'ordering': ['session__session_date', 'enrollment__beneficiary__full_name'],
                'unique_together': {('session', 'enrollment')},
            },
        ),
    ]
