# Generated by Django 4.2.13 on 2025-07-29 20:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="project",
            managers=[
                ("optimized_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
