# Generated by Django 4.2.23 on 2025-06-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
    ]
