# Generated by Django 4.2.13 on 2025-07-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('sanitized_filename', models.CharField(max_length=255, verbose_name='Nome Sanitizado')),
                ('file_path', models.CharField(max_length=500, verbose_name='Caminho do Arquivo')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamanho (bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('file_type', models.CharField(choices=[('document', 'Documento'), ('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('other', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('file_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash SHA-256')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhado'), ('virus_detected', 'Vírus Detectado')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('virus_scan_result', models.JSONField(default=dict, verbose_name='Resultado do Scan')),
                ('validation_errors', models.JSONField(default=list, verbose_name='Erros de Validação')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Conteúdo')),
            ],
            options={
                'verbose_name': 'Arquivo Enviado',
                'verbose_name_plural': 'Arquivos Enviados',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
