# Generated by Django 4.2.23 on 2025-06-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
