# Generated by Django 4.2.13 on 2025-07-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data do Registro')),
                ('description', models.TextField(verbose_name='Descrição da Evolução')),
                ('signature_required', models.BooleanField(default=False, verbose_name='Requer Assinatura da Beneficiária')),
                ('signed_by_beneficiary', models.BooleanField(default=False, verbose_name='Assinado pela Beneficiária')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Registro de Evolução',
                'verbose_name_plural': 'Registros de Evolução',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
