# Generated by Django 4.2.13 on 2025-07-24 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("social", "0001_initial"),
        ("projects", "0001_initial"),
        ("workshops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvolutionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data do Registro")),
                ("description", models.TextField(verbose_name="Descrição da Evolução")),
                (
                    "signature_required",
                    models.BooleanField(
                        default=False, verbose_name="Requer Assinatura da Beneficiária"
                    ),
                ),
                (
                    "signed_by_beneficiary",
                    models.BooleanField(
                        default=False, verbose_name="Assinado pela Beneficiária"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "evidence",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="evolution_evidence/",
                        verbose_name="Documento/Evidência",
                    ),
                ),
                (
                    "anamneses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="evolution_records",
                        to="social.socialanamnesis",
                        verbose_name="Anamneses Relacionadas",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evolution_records_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evolution_records",
                        to="members.beneficiary",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="evolution_records",
                        to="projects.project",
                        verbose_name="Projetos Relacionados",
                    ),
                ),
                (
                    "workshops",
                    models.ManyToManyField(
                        blank=True,
                        related_name="evolution_records",
                        to="workshops.workshop",
                        verbose_name="Oficinas Relacionadas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Evolução",
                "verbose_name_plural": "Registros de Evolução",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
