# Generated by Django 4.2.13 on 2025-07-11 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evolution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolutionrecord',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolution_records_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evolutionrecord',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_records', to='members.beneficiary'),
        ),
    ]
