# Generated by Django 4.2.13 on 2025-07-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('workshops', '0001_initial'),
        ('social', '0012_alter_familymember_options_and_more'),
        ('evolution', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolutionrecord',
            name='anamneses',
            field=models.ManyToManyField(blank=True, related_name='evolution_records', to='social.socialanamnesis', verbose_name='Anamneses Relacionadas'),
        ),
        migrations.AddField(
            model_name='evolutionrecord',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evolution_evidence/', verbose_name='Documento/Evidência'),
        ),
        migrations.AddField(
            model_name='evolutionrecord',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='evolution_records', to='projects.project', verbose_name='Projetos Relacionados'),
        ),
        migrations.AddField(
            model_name='evolutionrecord',
            name='workshops',
            field=models.ManyToManyField(blank=True, related_name='evolution_records', to='workshops.workshop', verbose_name='Oficinas Relacionadas'),
        ),
    ]
