# Generated by Django 4.2.7 on 2025-06-15 00:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Oficina')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('workshop_type', models.CharField(choices=[('artesanato', 'Artesanato'), ('culinaria', 'Culinária'), ('costura', 'Costura'), ('informatica', 'Informática'), ('empreendedorismo', 'Empreendedorismo'), ('capacitacao', 'Capacitação Profissional'), ('terapeutica', 'Terapêutica'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Oficina')),
                ('facilitator', models.CharField(max_length=100, verbose_name='Facilitador(a)')),
                ('location', models.CharField(max_length=200, verbose_name='Local')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('planejamento', 'Em Planejamento'), ('ativo', 'Ativo'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejamento', max_length=20, verbose_name='Status')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Máximo de Participantes')),
                ('objectives', models.TextField(verbose_name='Objetivos da Oficina')),
                ('materials_needed', models.TextField(blank=True, verbose_name='Materiais Necessários')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='Data de Inscrição')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('concluido', 'Concluído'), ('desistente', 'Desistente'), ('transferido', 'Transferido')], default='ativo', max_length=20, verbose_name='Status')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota Final')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Certificado Emitido')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_enrollments', to='members.beneficiary')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Inscrição em Oficina',
                'verbose_name_plural': 'Inscrições em Oficinas',
                'ordering': ['-enrollment_date'],
                'unique_together': {('workshop', 'beneficiary')},
            },
        ),
        migrations.CreateModel(
            name='WorkshopSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField(verbose_name='Número da Sessão')),
                ('date', models.DateField(verbose_name='Data da Sessão')),
                ('start_time', models.TimeField(verbose_name='Horário de Início')),
                ('end_time', models.TimeField(verbose_name='Horário de Término')),
                ('topic', models.CharField(max_length=200, verbose_name='Tópico/Tema')),
                ('content_covered', models.TextField(blank=True, verbose_name='Conteúdo Abordado')),
                ('materials_used', models.TextField(blank=True, verbose_name='Materiais Utilizados')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Sessão da Oficina',
                'verbose_name_plural': 'Sessões da Oficina',
                'ordering': ['session_number'],
                'unique_together': {('workshop', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='WorkshopEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('inicial', 'Avaliação Inicial'), ('processual', 'Avaliação Processual'), ('final', 'Avaliação Final')], max_length=20, verbose_name='Tipo de Avaliação')),
                ('date', models.DateField(verbose_name='Data da Avaliação')),
                ('technical_skills', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Habilidades Técnicas')),
                ('creativity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Criatividade')),
                ('participation', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Participação')),
                ('collaboration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Colaboração')),
                ('punctuality', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Pontualidade')),
                ('strengths', models.TextField(verbose_name='Pontos Fortes')),
                ('improvement_areas', models.TextField(verbose_name='Áreas para Melhoria')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendações')),
                ('evaluator', models.CharField(max_length=100, verbose_name='Avaliador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='workshops.workshopenrollment')),
            ],
            options={
                'verbose_name': 'Avaliação de Oficina',
                'verbose_name_plural': 'Avaliações de Oficinas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False, verbose_name='Presente')),
                ('late', models.BooleanField(default=False, verbose_name='Chegou Atrasado')),
                ('left_early', models.BooleanField(default=False, verbose_name='Saiu Mais Cedo')),
                ('participation_quality', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('boa', 'Boa'), ('regular', 'Regular'), ('baixa', 'Baixa')], max_length=20, verbose_name='Qualidade da Participação')),
                ('notes', models.TextField(blank=True, verbose_name='Observações sobre a Participação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='workshops.workshopenrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='workshops.workshopsession')),
            ],
            options={
                'verbose_name': 'Presença em Sessão',
                'verbose_name_plural': 'Presenças em Sessões',
                'ordering': ['session__session_number'],
                'unique_together': {('session', 'enrollment')},
            },
        ),
    ]
