# Generated by Django 4.2.13 on 2025-06-18 13:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_add_status_to_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Oficina')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('workshop_type', models.CharField(choices=[('artesanato', 'Artesanato'), ('culinaria', 'Culinária'), ('costura', 'Costura'), ('informatica', 'Informática'), ('empreendedorismo', 'Empreendedorismo'), ('capacitacao', 'Capacitação Profissional'), ('terapeutica', 'Terapêutica'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Oficina')),
                ('facilitator', models.CharField(max_length=100, verbose_name='Facilitador(a)')),
                ('location', models.CharField(max_length=200, verbose_name='Local')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('planejamento', 'Em Planejamento'), ('ativo', 'Ativo'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejamento', max_length=20, verbose_name='Status')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Máximo de Participantes')),
                ('objectives', models.TextField(verbose_name='Objetivos da Oficina')),
                ('materials_needed', models.TextField(blank=True, verbose_name='Materiais Necessários')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='Data de Inscrição')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('concluido', 'Concluído'), ('desistente', 'Desistente'), ('transferido', 'Transferido')], default='ativo', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_enrollments', to='members.beneficiary')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Inscrição em Oficina',
                'verbose_name_plural': 'Inscrições em Oficinas',
                'ordering': ['-enrollment_date'],
                'unique_together': {('workshop', 'beneficiary')},
            },
        ),
        migrations.CreateModel(
            name='WorkshopSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='Data da Sessão')),
                ('start_time', models.TimeField(verbose_name='Horário de Início')),
                ('end_time', models.TimeField(verbose_name='Horário de Término')),
                ('topic', models.CharField(max_length=200, verbose_name='Tópico/Tema')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Sessão da Oficina',
                'verbose_name_plural': 'Sessões da Oficina',
                'ordering': ['session_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação (1-5)')),
                ('feedback', models.TextField(verbose_name='Feedback sobre a oficina')),
                ('suggestions', models.TextField(blank=True, verbose_name='Sugestões para melhorias')),
                ('evaluation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='workshops.workshopenrollment')),
            ],
            options={
                'verbose_name': 'Avaliação de Oficina',
                'verbose_name_plural': 'Avaliações de Oficinas',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False, verbose_name='Presente')),
                ('notes', models.TextField(blank=True, verbose_name='Observações sobre a Participação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='workshops.workshopenrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='workshops.workshopsession')),
            ],
            options={
                'verbose_name': 'Presença em Sessão',
                'verbose_name_plural': 'Presenças em Sessões',
                'ordering': ['session__session_date'],
                'unique_together': {('session', 'enrollment')},
            },
        ),
    ]
