# Generated by Django 4.2.13 on 2025-07-31 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0002_alter_workshop_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="workshop",
            managers=[],
        ),
    ]
