# Generated by Django 4.2.7 on 2025-06-14 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelOfLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Avaliação')),
                ('family', models.FloatField(help_text='Avaliação de 0 a 10', verbose_name='Família')),
                ('finance', models.FloatField(help_text='Avaliação de 0 a 10', verbose_name='Finanças')),
                ('health', models.FloatField(help_text='Avaliação de 0 a 10', verbose_name='Saúde')),
                ('career', models.FloatField(help_text='Avaliação de 0 a 10', verbose_name='Carreira')),
                ('relationships', models.FloatField(help_text='Avaliação de 0 a 10', verbose_name='Relacionamentos')),
                ('personal_growth', models.FloatField(help_text='Avaliação de 0 a 10', verbose_name='Crescimento Pessoal')),
                ('leisure', models.FloatField(help_text='Avaliação de 0 a 10', verbose_name='Lazer')),
                ('spirituality', models.FloatField(help_text='Avaliação de 0 a 10', verbose_name='Espiritualidade')),
                ('education', models.FloatField(help_text='Avaliação de 0 a 10', verbose_name='Educação')),
                ('environment', models.FloatField(help_text='Avaliação de 0 a 10', verbose_name='Meio Ambiente')),
                ('contribution', models.FloatField(help_text='Avaliação de 0 a 10', verbose_name='Contribuição Social')),
                ('emotions', models.FloatField(help_text='Avaliação de 0 a 10', verbose_name='Equilíbrio Emocional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_of_life', to='members.beneficiary')),
            ],
            options={
                'verbose_name': 'Roda da Vida',
                'verbose_name_plural': 'Rodas da Vida',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_goal', models.TextField(verbose_name='Objetivo Principal')),
                ('priority_areas', models.JSONField(default=list, help_text='Lista de áreas prioritárias', verbose_name='Áreas Prioritárias')),
                ('actions', models.JSONField(default=dict, help_text='Detalhamento das ações planejadas', verbose_name='Plano de Ações')),
                ('institute_support', models.TextField(verbose_name='Apoio Institucional Necessário')),
                ('semester_review', models.TextField(blank=True, verbose_name='Revisão Semestral')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='members.beneficiary')),
            ],
            options={
                'verbose_name': 'Plano de Ação',
                'verbose_name_plural': 'Planos de Ação',
                'ordering': ['-created_at'],
            },
        ),
    ]
