# Generated by Django 4.2.7 on 2025-06-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='actions',
            field=models.TextField(help_text='Detalhamento das ações planejadas', verbose_name='Plano de Ações'),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='priority_areas',
            field=models.TextField(help_text='Lista de áreas prioritárias (separadas por vírgula ou quebra de linha)', verbose_name='Áreas Prioritárias'),
        ),
    ]
