# Generated by Django 4.2.13 on 2025-07-24 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do Canal"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("public", "Público"),
                            ("private", "Privado"),
                            ("department", "Departamento"),
                            ("project", "Projeto"),
                            ("task", "Tarefa"),
                            ("direct", "Mensagem Direta"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Arquivado"),
                ),
                (
                    "max_members",
                    models.IntegerField(default=100, verbose_name="Máximo de Membros"),
                ),
                (
                    "allow_threads",
                    models.BooleanField(default=True, verbose_name="Permitir Threads"),
                ),
                (
                    "allow_reactions",
                    models.BooleanField(default=True, verbose_name="Permitir Reações"),
                ),
                (
                    "allow_file_sharing",
                    models.BooleanField(
                        default=True,
                        verbose_name="Permitir Compartilhamento de Arquivos",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_chat_channels",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_channels",
                        to="hr.department",
                        verbose_name="Departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canal de Chat",
                "verbose_name_plural": "Canais de Chat",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="Mensagem")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("file", "Arquivo"),
                            ("image", "Imagem"),
                            ("system", "Sistema"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="chat/attachments/",
                        verbose_name="Anexo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="Editado"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatchannel",
                        verbose_name="Canal",
                    ),
                ),
                (
                    "mentions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mentioned_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Menções",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="chat.chatmessage",
                        verbose_name="Resposta a",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Remetente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Título"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="chat.chatchannel",
                        verbose_name="Canal",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_threads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread",
                        to="chat.chatmessage",
                        verbose_name="Mensagem Pai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread",
                "verbose_name_plural": "Threads",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("task", "Tarefas"),
                            ("project", "Projetos"),
                            ("calendar", "Calendário"),
                            ("email", "Email"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(default=dict, verbose_name="Configuração"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="chat.chatchannel",
                        verbose_name="Canal",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_integrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integração",
                "verbose_name_plural": "Integrações",
            },
        ),
        migrations.CreateModel(
            name="ChatChannelMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Membro"),
                            ("admin", "Administrador"),
                            ("moderator", "Moderador"),
                            ("guest", "Convidado"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="Papel",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Entrou em"),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última leitura"
                    ),
                ),
                (
                    "is_muted",
                    models.BooleanField(default=False, verbose_name="Silenciado"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Fixado"),
                ),
                (
                    "notification_level",
                    models.CharField(
                        choices=[
                            ("all", "Todas"),
                            ("mentions", "Apenas Menções"),
                            ("none", "Nenhuma"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Nível de Notificação",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="chat.chatchannel",
                        verbose_name="Canal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro do Canal",
                "verbose_name_plural": "Membros do Canal",
                "unique_together": {("channel", "user")},
            },
        ),
        migrations.AddField(
            model_name="chatchannel",
            name="members",
            field=models.ManyToManyField(
                related_name="chat_channels",
                through="chat.ChatChannelMembership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Membros",
            ),
        ),
        migrations.AddField(
            model_name="chatchannel",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_channels",
                to="projects.project",
                verbose_name="Projeto",
            ),
        ),
        migrations.AddField(
            model_name="chatchannel",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_channels",
                to="tasks.task",
                verbose_name="Tarefa",
            ),
        ),
        migrations.CreateModel(
            name="ChatBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("commands", models.JSONField(default=dict, verbose_name="Comandos")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "channels",
                    models.ManyToManyField(
                        related_name="bots",
                        to="chat.chatchannel",
                        verbose_name="Canais",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_bots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_bot",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot",
                "verbose_name_plural": "Bots",
            },
        ),
        migrations.CreateModel(
            name="ChatReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction",
                    models.CharField(
                        choices=[
                            ("👍", "Curtir"),
                            ("👎", "Não Curtir"),
                            ("😄", "Feliz"),
                            ("😢", "Triste"),
                            ("😲", "Surpreso"),
                            ("❤️", "Coração"),
                            ("🚀", "Foguete"),
                            ("👏", "Palmas"),
                            ("🎉", "Festa"),
                            ("✅", "Concluído"),
                        ],
                        max_length=10,
                        verbose_name="Reação",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="chat.chatmessage",
                        verbose_name="Mensagem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reação",
                "verbose_name_plural": "Reações",
                "unique_together": {("message", "user", "reaction")},
            },
        ),
        migrations.CreateModel(
            name="ChatMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lido")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "mentioned_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_mentions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Mencionado",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_mentions",
                        to="chat.chatmessage",
                        verbose_name="Mensagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menção",
                "verbose_name_plural": "Menções",
                "unique_together": {("message", "mentioned_user")},
            },
        ),
        migrations.CreateModel(
            name="ChatAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "message_count",
                    models.IntegerField(default=0, verbose_name="Mensagens"),
                ),
                (
                    "active_users",
                    models.IntegerField(default=0, verbose_name="Usuários Ativos"),
                ),
                (
                    "file_shares",
                    models.IntegerField(
                        default=0, verbose_name="Arquivos Compartilhados"
                    ),
                ),
                (
                    "reactions_count",
                    models.IntegerField(default=0, verbose_name="Reações"),
                ),
                (
                    "thread_count",
                    models.IntegerField(default=0, verbose_name="Threads"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="chat.chatchannel",
                        verbose_name="Canal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics do Chat",
                "verbose_name_plural": "Analytics do Chat",
                "unique_together": {("channel", "date")},
            },
        ),
    ]
