# Generated by Django 4.2.13 on 2025-07-11 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Mensagem')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('file', 'Arquivo'), ('image', 'Imagem'), ('system', 'Sistema')], default='text', max_length=20, verbose_name='Tipo')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat/attachments/', verbose_name='Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Editado')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentioned_messages', to=settings.AUTH_USER_MODEL, verbose_name='Menções')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chat.chatmessage', verbose_name='Resposta a')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Sala')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('room_type', models.CharField(choices=[('general', 'Geral'), ('department', 'Departamento'), ('project', 'Projeto'), ('private', 'Privado'), ('task', 'Tarefa')], default='general', max_length=20, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arquivado')),
                ('max_members', models.IntegerField(default=50, verbose_name='Máximo de Membros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='hr.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificações por Email')),
                ('desktop_notifications', models.BooleanField(default=True, verbose_name='Notificações Desktop')),
                ('sound_notifications', models.BooleanField(default=True, verbose_name='Notificações Sonoras')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10, verbose_name='Tema')),
                ('language', models.CharField(default='pt-br', max_length=5, verbose_name='Idioma')),
                ('show_online_status', models.BooleanField(default=True, verbose_name='Mostrar Status Online')),
                ('allow_direct_messages', models.BooleanField(default=True, verbose_name='Permitir Mensagens Diretas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configurações do Chat',
                'verbose_name_plural': 'Configurações do Chat',
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Membro'), ('admin', 'Administrador'), ('moderator', 'Moderador')], default='member', max_length=20, verbose_name='Papel')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Entrou em')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='Última leitura')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Silenciado')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom', verbose_name='Sala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Membro da Sala',
                'verbose_name_plural': 'Membros das Salas',
                'unique_together': {('user', 'room')},
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='chat_rooms', through='chat.ChatRoomMembership', to=settings.AUTH_USER_MODEL, verbose_name='Membros'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='projects.project', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='tasks.task', verbose_name='Tarefa'),
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_message', 'Nova Mensagem'), ('mention', 'Menção'), ('room_created', 'Sala Criada'), ('member_added', 'Membro Adicionado'), ('member_removed', 'Membro Removido')], max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.chatmessage', verbose_name='Mensagem')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.chatroom', verbose_name='Sala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação do Chat',
                'verbose_name_plural': 'Notificações do Chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remetente'),
        ),
        migrations.CreateModel(
            name='ChatMessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('👍', 'Curtir'), ('👎', 'Não curtir'), ('❤️', 'Amar'), ('😂', 'Rir'), ('😮', 'Surpreso'), ('😢', 'Triste'), ('😡', 'Raiva'), ('🎉', 'Celebrar'), ('✅', 'Confirmar'), ('❌', 'Rejeitar')], max_length=10, verbose_name='Reação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.chatmessage', verbose_name='Mensagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Reação',
                'verbose_name_plural': 'Reações',
                'unique_together': {('message', 'user', 'reaction')},
            },
        ),
    ]
