# Generated by Django 4.2.13 on 2025-07-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('course', 'Curso'), ('participation', 'Participação'), ('completion', 'Conclusão'), ('achievement', 'Conquista'), ('declaration', 'Declaração de Comparecimento'), ('benefit_receipt', 'Recibo de Benefício')], default='workshop', max_length=20),
        ),
    ]
