# Generated by Django 4.2.13 on 2025-07-11 18:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='Resumo')),
                ('category', models.CharField(choices=[('general', 'Geral'), ('policy', 'Política'), ('event', 'Evento'), ('training', 'Treinamento'), ('safety', 'Segurança'), ('hr', 'Recursos Humanos'), ('technical', 'Técnico'), ('financial', 'Financeiro')], default='general', max_length=20, verbose_name='Categoria')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('is_global', models.BooleanField(default=False, verbose_name='Global (Todos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Fixado')),
                ('requires_acknowledgment', models.BooleanField(default=False, verbose_name='Requer Confirmação de Leitura')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('departments', models.ManyToManyField(blank=True, related_name='announcements', to='hr.department', verbose_name='Departamentos')),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Específicos')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-is_pinned', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='InternalMemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memo_number', models.CharField(max_length=50, unique=True, verbose_name='Número do Memorando')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('memo_type', models.CharField(choices=[('informative', 'Informativo'), ('directive', 'Diretivo'), ('request', 'Solicitação'), ('policy', 'Política'), ('procedure', 'Procedimento')], default='informative', max_length=20, verbose_name='Tipo')),
                ('requires_response', models.BooleanField(default=False, verbose_name='Requer Resposta')),
                ('response_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Prazo de Resposta')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Confidencial')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_memos', to='hr.department', verbose_name='Departamento Origem')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_memos', to=settings.AUTH_USER_MODEL, verbose_name='De')),
                ('to_departments', models.ManyToManyField(blank=True, related_name='received_memos', to='hr.department', verbose_name='Para Departamentos')),
                ('to_users', models.ManyToManyField(blank=True, related_name='received_memos', to=settings.AUTH_USER_MODEL, verbose_name='Para Usuários')),
            ],
            options={
                'verbose_name': 'Memorando',
                'verbose_name_plural': 'Memorandos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('suggestion_type', models.CharField(choices=[('improvement', 'Melhoria'), ('complaint', 'Reclamação'), ('idea', 'Ideia'), ('feedback', 'Feedback'), ('other', 'Outro')], default='improvement', max_length=20, verbose_name='Tipo')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anônimo')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('under_review', 'Em Análise'), ('in_progress', 'Em Andamento'), ('implemented', 'Implementado'), ('rejected', 'Rejeitado'), ('closed', 'Fechado')], default='open', max_length=20, verbose_name='Status')),
                ('response', models.TextField(blank=True, verbose_name='Resposta')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='hr.department', verbose_name='Departamento')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
            ],
            options={
                'verbose_name': 'Sugestão',
                'verbose_name_plural': 'Sugestões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='Resumo')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='MemoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Resposta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='communication.internalmemo', verbose_name='Memorando')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo_responses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resposta ao Memorando',
                'verbose_name_plural': 'Respostas aos Memorandos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_announcements', models.BooleanField(default=True, verbose_name='Comunicados por Email')),
                ('email_memos', models.BooleanField(default=True, verbose_name='Memorandos por Email')),
                ('email_newsletters', models.BooleanField(default=False, verbose_name='Newsletters por Email')),
                ('digest_frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('never', 'Nunca')], default='weekly', max_length=10, verbose_name='Frequência do Resumo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_settings', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configurações de Comunicação',
                'verbose_name_plural': 'Configurações de Comunicação',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='communication/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif', 'zip', 'rar'])], verbose_name='Arquivo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communication.announcement', verbose_name='Comunicado')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Lido em')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='communication.announcement', verbose_name='Comunicado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Confirmação de Leitura',
                'verbose_name_plural': 'Confirmações de Leitura',
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
