# Generated by Django 4.2.13 on 2025-07-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_communication_refactored'),
        ('communication', '0002_communicationcampaign_communicationtemplate_and_more'),
    ]

    operations = [
    ]
