# Generated by Django 4.2.13 on 2025-07-15 17:19
# Safe migration to avoid index renaming issues

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0003_merge_20250715_1403'),
    ]

    operations = [
        # Create new CommunicationAnalyticsRefactored model
        migrations.CreateModel(
            name='CommunicationAnalyticsRefactored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, verbose_name='Nome da Métrica')),
                ('metric_value', models.JSONField(verbose_name='Valor da Métrica')),
                ('period_start', models.DateTimeField(verbose_name='Início do Período')),
                ('period_end', models.DateTimeField(verbose_name='Fim do Período')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communication.communicationmessage', verbose_name='Mensagem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Analítica de Comunicação Refatorada',
                'verbose_name_plural': 'Analíticas de Comunicação Refatoradas',
                'ordering': ['-created_at'],
            },
        ),
        
        # Update CommunicationAnalytics fields safely
        migrations.AlterModelOptions(
            name='communicationanalytics',
            options={'verbose_name': 'Analytics de Comunicação', 'verbose_name_plural': 'Analytics de Comunicação'},
        ),
        
        # Add new fields to CommunicationAnalytics
        migrations.AddField(
            model_name='communicationanalytics',
            name='bounced_count',
            field=models.IntegerField(default=0, verbose_name='Devolvidos'),
        ),
        migrations.AddField(
            model_name='communicationanalytics',
            name='clicked_count',
            field=models.IntegerField(default=0, verbose_name='Cliques'),
        ),
        migrations.AddField(
            model_name='communicationanalytics',
            name='delivered_count',
            field=models.IntegerField(default=0, verbose_name='Entregues'),
        ),
        migrations.AddField(
            model_name='communicationanalytics',
            name='opened_count',
            field=models.IntegerField(default=0, verbose_name='Abertos'),
        ),
        migrations.AddField(
            model_name='communicationanalytics',
            name='sent_count',
            field=models.IntegerField(default=0, verbose_name='Enviados'),
        ),
        migrations.AddField(
            model_name='communicationanalytics',
            name='unique_clicks',
            field=models.IntegerField(default=0, verbose_name='Cliques Únicos'),
        ),
        migrations.AddField(
            model_name='communicationanalytics',
            name='unique_opens',
            field=models.IntegerField(default=0, verbose_name='Aberturas Únicas'),
        ),
        migrations.AddField(
            model_name='communicationanalytics',
            name='unsubscribed_count',
            field=models.IntegerField(default=0, verbose_name='Descadastrados'),
        ),
        migrations.AddField(
            model_name='communicationanalytics',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communicationanalytics',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communication.communicationcampaign', verbose_name='Campanha'),
        ),
    ]
