# Generated by Django 4.2.13 on 2025-07-16 15:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0004_safe_migration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communicationmessage',
            new_name='communicati_status_01a21a_idx',
            old_name='communication_msg_status_publish_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationmessage',
            new_name='communicati_author__389cbb_idx',
            old_name='communication_msg_author_created_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationmessage',
            new_name='communicati_message_a1b8a4_idx',
            old_name='communication_msg_type_category_idx',
        ),
        migrations.RenameIndex(
            model_name='messagerecipient',
            new_name='communicati_user_id_d50c8a_idx',
            old_name='communication_recipient_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='messagerecipient',
            new_name='communicati_message_46c438_idx',
            old_name='communication_recipient_msg_delivery_idx',
        ),
        migrations.RenameIndex(
            model_name='messageresponse',
            new_name='communicati_message_b3745b_idx',
            old_name='communication_response_msg_created_idx',
        ),
        migrations.RenameIndex(
            model_name='messageresponse',
            new_name='communicati_user_id_5a6c49_idx',
            old_name='communication_response_user_type_idx',
        ),
        migrations.RemoveField(
            model_name='communicationanalytics',
            name='message',
        ),
        migrations.RemoveField(
            model_name='communicationanalytics',
            name='metric_name',
        ),
        migrations.RemoveField(
            model_name='communicationanalytics',
            name='metric_value',
        ),
        migrations.RemoveField(
            model_name='communicationanalytics',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='communicationanalytics',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='communicationanalytics',
            name='user',
        ),
        migrations.AlterField(
            model_name='communicationanalytics',
            name='bounced_count',
            field=models.IntegerField(default=0, verbose_name='Rejeitados'),
        ),
        migrations.AlterField(
            model_name='communicationanalytics',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='communication.communicationcampaign', verbose_name='Campanha'),
        ),
        migrations.AlterField(
            model_name='communicationanalytics',
            name='clicked_count',
            field=models.IntegerField(default=0, verbose_name='Clicados'),
        ),
        migrations.AlterField(
            model_name='communicationanalytics',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='communicationanalyticsrefactored',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_refactored', to='communication.communicationmessage', verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='communicationanalyticsrefactored',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_analytics_refactored', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='communicationevent',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='communication.communicationcampaign', verbose_name='Campanha'),
        ),
        migrations.AlterField(
            model_name='communicationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preferences_legacy', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(upload_to='communication/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png', 'gif'])], verbose_name='Arquivo'),
        ),
    ]
