# Generated by Django 4.2.13 on 2025-07-11 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0002_advancedtraining_onboardingprogram_onboardingtask_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklabel',
            options={'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
        migrations.AddField(
            model_name='taskboard',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor de Fundo'),
        ),
        migrations.AddField(
            model_name='taskboard',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='É Template'),
        ),
        migrations.AddField(
            model_name='taskcolumn',
            name='wip_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Work In Progress limit', null=True, verbose_name='Limite WIP'),
        ),
        migrations.AlterUniqueTogether(
            name='tasklabel',
            unique_together={('name', 'board')},
        ),
        migrations.CreateModel(
            name='TaskTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Início')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duração (minutos)')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_billable', models.BooleanField(default=True, verbose_name='Faturável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tasks.task', verbose_name='Tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Tempo',
                'verbose_name_plural': 'Registros de Tempo',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Template')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('title_template', models.CharField(max_length=200, verbose_name='Modelo de Título')),
                ('description_template', models.TextField(blank=True, verbose_name='Modelo de Descrição')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridade')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas Estimadas')),
                ('tags', models.CharField(blank=True, help_text='Separadas por vírgula', max_length=500, verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='hr.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Template de Tarefa',
                'verbose_name_plural': 'Templates de Tarefas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Diária'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20, verbose_name='Frequência')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('next_occurrence', models.DateField(verbose_name='Próxima Ocorrência')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='tasks.taskboard', verbose_name='Quadro')),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='tasks.tasktemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Tarefa Recorrente',
                'verbose_name_plural': 'Tarefas Recorrentes',
            },
        ),
        migrations.CreateModel(
            name='TaskAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Automação')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('trigger', models.CharField(choices=[('task_created', 'Tarefa Criada'), ('task_moved', 'Tarefa Movida'), ('task_completed', 'Tarefa Concluída'), ('due_date_approaching', 'Prazo Próximo'), ('overdue', 'Atrasada')], max_length=30, verbose_name='Gatilho')),
                ('action', models.CharField(choices=[('create_task', 'Criar Tarefa'), ('assign_user', 'Atribuir Usuário'), ('send_notification', 'Enviar Notificação'), ('change_priority', 'Alterar Prioridade'), ('move_to_column', 'Mover para Coluna'), ('add_comment', 'Adicionar Comentário')], max_length=30, verbose_name='Ação')),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name='Condições')),
                ('action_data', models.JSONField(blank=True, default=dict, verbose_name='Dados da Ação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='tasks.taskboard', verbose_name='Quadro')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_automations', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Automação',
                'verbose_name_plural': 'Automações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='tasklabel',
            name='tasks',
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('blocks', 'Bloqueia'), ('depends_on', 'Depende de'), ('related', 'Relacionada')], default='depends_on', max_length=20, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dependencies', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='tasks.task', verbose_name='Depende de')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='tasks.task', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Dependência',
                'verbose_name_plural': 'Dependências',
                'unique_together': {('task', 'depends_on')},
            },
        ),
    ]
