# Generated by Django 4.2.13 on 2025-07-12 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_tasklabel_options_taskboard_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_task_templates', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
