# Generated by Django 4.2.13 on 2025-07-24 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAnamnesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Renda familiar",
                    ),
                ),
                (
                    "housing_situation",
                    models.TextField(
                        help_text="Descreva a situação habitacional da beneficiária",
                        verbose_name="Situação habitacional",
                    ),
                ),
                (
                    "support_network",
                    models.TextField(
                        help_text="Descreva a rede de apoio social da beneficiária",
                        verbose_name="Rede de apoio",
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True,
                        help_text="Observações adicionais sobre a anamnese",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("completed", "Concluída"),
                            ("requires_update", "Requer Atualização"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "signed_by_beneficiary",
                    models.BooleanField(
                        default=False, verbose_name="Assinado pela Beneficiária"
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False, verbose_name="Bloqueado para Edição"
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_anamneses",
                        to="members.beneficiary",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_social_anamnesis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_by_technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="social_anamneses_signed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anamnese Social",
                "verbose_name_plural": "Anamneses Sociais",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Cor em formato hexadecimal (#000000)",
                        max_length=7,
                        verbose_name="Cor identificadora",
                    ),
                ),
                (
                    "priority_level",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1 = Baixa, 2 = Média, 3 = Alta",
                        verbose_name="Nível de prioridade",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoria de Vulnerabilidade",
                "verbose_name_plural": "Categorias de Vulnerabilidades",
                "ordering": ["-priority_level", "name"],
            },
        ),
        migrations.CreateModel(
            name="SocialAnamnesisEvolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evolution_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("description", models.TextField(verbose_name="Descrição da evolução")),
                (
                    "changes_in_family",
                    models.TextField(
                        blank=True,
                        help_text="Descreva mudanças na composição familiar",
                        verbose_name="Mudanças na família",
                    ),
                ),
                (
                    "changes_in_vulnerabilities",
                    models.TextField(
                        blank=True,
                        help_text="Descreva mudanças nas vulnerabilidades",
                        verbose_name="Mudanças nas vulnerabilidades",
                    ),
                ),
                (
                    "changes_in_support_network",
                    models.TextField(
                        blank=True,
                        help_text="Descreva mudanças na rede de apoio",
                        verbose_name="Mudanças na rede de apoio",
                    ),
                ),
                (
                    "attachments",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="social_anamnesis_evolutions/",
                        verbose_name="Anexos",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anamnesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evolutions",
                        to="social.socialanamnesis",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_anamnesis_evolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evolução da Anamnese",
                "verbose_name_plural": "Evoluções da Anamnese",
                "ordering": ["-evolution_date"],
            },
        ),
        migrations.CreateModel(
            name="IdentifiedVulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrição detalhada")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Média"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Gravidade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Identificada"),
                            ("in_progress", "Em Acompanhamento"),
                            ("resolved", "Resolvida"),
                            ("requires_attention", "Requer Atenção"),
                        ],
                        default="identified",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "intervention_needed",
                    models.TextField(
                        blank=True,
                        help_text="Descreva que tipo de intervenção é necessária",
                        verbose_name="Intervenção necessária",
                    ),
                ),
                (
                    "priority_date",
                    models.DateField(
                        blank=True,
                        help_text="Data até quando esta vulnerabilidade deve ser abordada",
                        null=True,
                        verbose_name="Data de prioridade",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anamnesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="social.socialanamnesis",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identified_vulnerabilities",
                        to="social.vulnerabilitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerabilidade Identificada",
                "verbose_name_plural": "Vulnerabilidades Identificadas",
                "ordering": ["-priority_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Cônjuge/Companheiro(a)"),
                            ("child", "Filho(a)"),
                            ("parent", "Pai/Mãe"),
                            ("sibling", "Irmão/Irmã"),
                            ("grandparent", "Avô/Avó"),
                            ("grandchild", "Neto(a)"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Parentesco",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Idade"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=1,
                        null=True,
                        verbose_name="Gênero",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "Sem escolaridade"),
                            ("elementary_incomplete", "Ensino fundamental incompleto"),
                            ("elementary_complete", "Ensino fundamental completo"),
                            ("high_school_incomplete", "Ensino médio incompleto"),
                            ("high_school_complete", "Ensino médio completo"),
                            (
                                "higher_education_incomplete",
                                "Ensino superior incompleto",
                            ),
                            ("higher_education_complete", "Ensino superior completo"),
                            ("postgraduate", "Pós-graduação"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="Nível de escolaridade",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ocupação"
                    ),
                ),
                (
                    "income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Renda individual",
                    ),
                ),
                (
                    "health_conditions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Condições de saúde"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anamnesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to="social.socialanamnesis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro da Família",
                "verbose_name_plural": "Membros da Família",
                "ordering": ["relationship", "name"],
            },
        ),
    ]
