# Generated by Django 4.2.7 on 2025-06-14 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAnamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Anamnese')),
                ('family_composition', models.JSONField(default=dict, help_text='Dados da família', verbose_name='Composição Familiar')),
                ('income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Renda Familiar')),
                ('vulnerabilities', models.TextField(verbose_name='Vulnerabilidades Identificadas')),
                ('substance_use', models.TextField(blank=True, verbose_name='Uso de Substâncias')),
                ('observations', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('signed_by_beneficiary', models.BooleanField(default=False, verbose_name='Assinado pela Beneficiária')),
                ('locked', models.BooleanField(default=False, verbose_name='Bloqueado para Edição')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_anamnesis', to='members.beneficiary')),
                ('signed_by_technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_anamnesis_signed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anamnese Social',
                'verbose_name_plural': 'Anamneses Sociais',
                'ordering': ['-date'],
            },
        ),
    ]
