# Generated by Django 4.2.13 on 2025-07-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialanamnesis",
            name="is_signed",
            field=models.BooleanField(
                default=False,
                help_text="Indica se a anamnese foi assinada digitalmente",
                verbose_name="Assinado Digitalmente",
            ),
        ),
        migrations.AddField(
            model_name="socialanamnesis",
            name="signature_beneficiary",
            field=models.TextField(
                blank=True,
                help_text="Canvas data da assinatura digital da beneficiária",
                verbose_name="Assinatura da Beneficiária",
            ),
        ),
        migrations.AddField(
            model_name="socialanamnesis",
            name="signature_technician",
            field=models.TextField(
                blank=True,
                help_text="Assinatura eletrônica da técnica responsável",
                verbose_name="Assinatura da Técnica",
            ),
        ),
        migrations.AddField(
            model_name="socialanamnesis",
            name="signature_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp certificado da assinatura",
                null=True,
                verbose_name="Data/Hora da Assinatura",
            ),
        ),
    ]
