# Generated by Django 4.2.7 on 2025-06-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialanamnesis',
            name='family_composition',
            field=models.TextField(help_text='Descrição da composição familiar', verbose_name='Composição Familiar'),
        ),
    ]
