# Generated by Django 4.2.13 on 2025-07-11 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialanamnesis',
            name='signed_by_technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_anamneses_signed', to=settings.AUTH_USER_MODEL),
        ),
    ]
