# Generated by Django 4.2.13 on 2025-07-15 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        # Primeiro, vamos dropar a tabela atual SocialAnamnesis
        migrations.RunSQL(
            "DROP TABLE IF EXISTS social_socialanamnesis;",
            reverse_sql="",
        ),
        
        # Recriamos a tabela com a nova estrutura
        migrations.CreateModel(
            name='SocialAnamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('responsible_professional', models.CharField(max_length=255, verbose_name='Profissional Responsável')),
                ('interview_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Entrevista')),
                ('interview_location', models.CharField(max_length=255, verbose_name='Local da Entrevista')),
                ('housing_situation', models.CharField(choices=[('propria', 'Casa Própria'), ('alugada', 'Casa Alugada'), ('cedida', 'Casa Cedida'), ('ocupacao', 'Ocupação'), ('rua', 'Situação de Rua'), ('abrigo', 'Abrigo/Instituição'), ('outros', 'Outros')], max_length=50, verbose_name='Situação de Moradia')),
                ('housing_condition', models.CharField(choices=[('adequada', 'Adequada'), ('precaria', 'Precária'), ('insalubre', 'Insalubre'), ('risco', 'Em Risco')], max_length=50, verbose_name='Condição da Moradia')),
                ('family_income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Renda Familiar')),
                ('income_source', models.CharField(max_length=255, verbose_name='Fonte de Renda')),
                ('receives_benefits', models.BooleanField(default=False, verbose_name='Recebe Benefícios')),
                ('benefits_description', models.TextField(blank=True, verbose_name='Descrição dos Benefícios')),
                ('education_level', models.CharField(choices=[('analfabeto', 'Analfabeto'), ('fundamental_incompleto', 'Fundamental Incompleto'), ('fundamental_completo', 'Fundamental Completo'), ('medio_incompleto', 'Médio Incompleto'), ('medio_completo', 'Médio Completo'), ('superior_incompleto', 'Superior Incompleto'), ('superior_completo', 'Superior Completo'), ('pos_graduacao', 'Pós-Graduação')], max_length=50, verbose_name='Nível de Escolaridade')),
                ('professional_situation', models.CharField(choices=[('empregada', 'Empregada'), ('desempregada', 'Desempregada'), ('autonoma', 'Autônoma'), ('aposentada', 'Aposentada'), ('estudante', 'Estudante'), ('dona_casa', 'Dona de Casa'), ('outros', 'Outros')], max_length=50, verbose_name='Situação Profissional')),
                ('health_condition', models.CharField(choices=[('otima', 'Ótima'), ('boa', 'Boa'), ('regular', 'Regular'), ('ruim', 'Ruim'), ('pessima', 'Péssima')], max_length=50, verbose_name='Condição de Saúde')),
                ('health_problems', models.TextField(blank=True, verbose_name='Problemas de Saúde')),
                ('uses_medications', models.BooleanField(default=False, verbose_name='Usa Medicamentos')),
                ('medications_description', models.TextField(blank=True, verbose_name='Descrição dos Medicamentos')),
                ('psychological_support', models.BooleanField(default=False, verbose_name='Recebe Apoio Psicológico')),
                ('substance_use', models.BooleanField(default=False, verbose_name='Uso de Substâncias')),
                ('substance_description', models.TextField(blank=True, verbose_name='Descrição do Uso de Substâncias')),
                ('violence_history', models.BooleanField(default=False, verbose_name='Histórico de Violência')),
                ('violence_description', models.TextField(blank=True, verbose_name='Descrição da Violência')),
                ('protection_network', models.TextField(blank=True, verbose_name='Rede de Proteção')),
                ('social_participation', models.TextField(blank=True, verbose_name='Participação Social')),
                ('expectations', models.TextField(blank=True, verbose_name='Expectativas')),
                ('goals', models.TextField(blank=True, verbose_name='Objetivos')),
                ('intervention_plan', models.TextField(blank=True, verbose_name='Plano de Intervenção')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('risk_level', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='medio', max_length=20, verbose_name='Nível de Risco')),
                ('priority', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('completed', 'Concluída'), ('review', 'Em Revisão'), ('approved', 'Aprovada')], default='draft', max_length=20, verbose_name='Status')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.beneficiary', verbose_name='Beneficiária')),
            ],
            options={
                'verbose_name': 'Anamnese Social',
                'verbose_name_plural': 'Anamneses Sociais',
                'ordering': ['-created_at'],
            },
        ),
        
        # Criamos os modelos auxiliares
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('age', models.PositiveIntegerField(verbose_name='Idade')),
                ('relationship', models.CharField(max_length=100, verbose_name='Parentesco')),
                ('occupation', models.CharField(blank=True, max_length=255, verbose_name='Ocupação')),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Renda')),
                ('education', models.CharField(blank=True, max_length=100, verbose_name='Escolaridade')),
                ('lives_together', models.BooleanField(default=True, verbose_name='Mora Junto')),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='social.socialanamnesis', verbose_name='Anamnese')),
            ],
            options={
                'verbose_name': 'Membro da Família',
                'verbose_name_plural': 'Membros da Família',
                'ordering': ['name'],
            },
        ),
        
        migrations.CreateModel(
            name='VulnerabilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Vulnerabilidade',
                'verbose_name_plural': 'Categorias de Vulnerabilidade',
                'ordering': ['name'],
            },
        ),
        
        migrations.CreateModel(
            name='IdentifiedVulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave'), ('critica', 'Crítica')], max_length=20, verbose_name='Gravidade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('intervention_needed', models.BooleanField(default=False, verbose_name='Intervenção Necessária')),
                ('intervention_description', models.TextField(blank=True, verbose_name='Descrição da Intervenção')),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='social.socialanamnesis', verbose_name='Anamnese')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.vulnerabilitycategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Vulnerabilidade Identificada',
                'verbose_name_plural': 'Vulnerabilidades Identificadas',
                'ordering': ['category__name'],
            },
        ),
        
        migrations.CreateModel(
            name='SocialAnamnesisEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('professional', models.CharField(max_length=255, verbose_name='Profissional')),
                ('evolution_type', models.CharField(choices=[('followup', 'Acompanhamento'), ('reassessment', 'Reavaliação'), ('intervention', 'Intervenção'), ('closure', 'Encerramento')], max_length=20, verbose_name='Tipo de Evolução')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('actions_taken', models.TextField(blank=True, verbose_name='Ações Realizadas')),
                ('next_steps', models.TextField(blank=True, verbose_name='Próximos Passos')),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to='social.socialanamnesis', verbose_name='Anamnese')),
            ],
            options={
                'verbose_name': 'Evolução da Anamnese Social',
                'verbose_name_plural': 'Evoluções da Anamnese Social',
                'ordering': ['-date'],
            },
        ),
    ]
