# Generated by Django 4.2.13 on 2025-07-29 20:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_socialanamnesis_is_signed_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="socialanamnesis",
            managers=[
                ("optimized_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
