# Generated by Django 4.2.13 on 2025-07-31 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_alter_socialanamnesis_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="socialanamnesis",
            managers=[],
        ),
    ]
