# Generated by Django 4.2.13 on 2025-07-15 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20250715_0844'),
    ]

    operations = [
        # Adicionar campos faltantes para VulnerabilityCategory
        migrations.AddField(
            model_name='vulnerabilitycategory',
            name='color',
            field=models.CharField(
                default='#6B7280',
                help_text='Cor em formato hexadecimal (#000000)',
                max_length=7,
                verbose_name='Cor identificadora'
            ),
        ),
        migrations.AddField(
            model_name='vulnerabilitycategory',
            name='priority_level',
            field=models.PositiveIntegerField(
                default=1,
                help_text='1 = Baixa, 2 = Média, 3 = Alta',
                verbose_name='Nível de prioridade'
            ),
        ),
        migrations.AddField(
            model_name='vulnerabilitycategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vulnerabilitycategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Adicionar campos faltantes para FamilyMember
        migrations.AddField(
            model_name='familymember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Adicionar campos faltantes para IdentifiedVulnerability
        migrations.AddField(
            model_name='identifiedvulnerability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='identifiedvulnerability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Adicionar campos faltantes para SocialAnamnesisEvolution
        migrations.AddField(
            model_name='socialanamnesis',
            name='technician_signature',
            field=models.CharField(blank=True, max_length=255, verbose_name='Assinatura do Técnico'),
        ),
        migrations.AddField(
            model_name='socialanamnesis',
            name='signature_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura'),
        ),
        migrations.AddField(
            model_name='socialanamnesis',
            name='beneficiary_signature',
            field=models.CharField(blank=True, max_length=255, verbose_name='Assinatura da Beneficiária'),
        ),
        migrations.AddField(
            model_name='socialanamnesis',
            name='beneficiary_signature_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura da Beneficiária'),
        ),
    ]
