# Generated by Django 4.2.13 on 2025-07-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20250715_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilitycategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
