# Generated by Django 4.2.13 on 2025-07-15 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20250715_0857'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        # Dropar a tabela atual
        migrations.RunSQL(
            "DROP TABLE IF EXISTS social_socialanamnesis;",
            reverse_sql="",
        ),
        
        # Recriar a tabela com a estrutura correta
        migrations.CreateModel(
            name='SocialAnamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('housing_situation', models.TextField(blank=True)),
                ('support_network', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído')], default='draft', max_length=20)),
                ('signed_by_beneficiary', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.beneficiary')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('signed_by_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_anamnesis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anamnese Social',
                'verbose_name_plural': 'Anamneses Sociais',
                'ordering': ['-created_at'],
            },
        ),
    ]
