# Generated by Django 4.2.13 on 2025-07-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_add_status_to_identifiedvulnerability'),
    ]

    operations = [
    ]
