# Generated by Django 4.2.13 on 2025-07-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20250715_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')],
                max_length=1,
                null=True,
                verbose_name='Gênero'
            ),
        ),
        migrations.AddField(
            model_name='familymember',
            name='education_level',
            field=models.CharField(
                blank=True,
                choices=[
                    ('none', 'Sem escolaridade'),
                    ('elementary_incomplete', 'Ensino fundamental incompleto'),
                    ('elementary_complete', 'Ensino fundamental completo'),
                    ('high_school_incomplete', 'Ensino médio incompleto'),
                    ('high_school_complete', 'Ensino médio completo'),
                    ('higher_education_incomplete', 'Ensino superior incompleto'),
                    ('higher_education_complete', 'Ensino superior completo'),
                    ('postgraduate', 'Pós-graduação'),
                ],
                max_length=30,
                null=True,
                verbose_name='Nível de escolaridade'
            ),
        ),
        migrations.AddField(
            model_name='familymember',
            name='health_conditions',
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name='Condições de saúde'
            ),
        ),
    ]
