# Generated by Django 4.2.7 on 2024-07-15 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0009_auto_20250715_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialanamnesisevolution',
            name='created_by',
            field=models.ForeignKey(
                default=1,  # Assumindo que existe um usuário com ID 1
                on_delete=django.db.models.deletion.CASCADE,
                related_name='social_anamnesis_evolutions',
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
