# Generated by Django 4.2.7 on 2024-07-15 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0010_add_created_by_to_socialanamnesisevolution'),
    ]

    operations = [
        # Adicionar o campo evolution_date
        migrations.AddField(
            model_name='socialanamnesisevolution',
            name='evolution_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        
        # Adicionar o campo changes_in_family
        migrations.AddField(
            model_name='socialanamnesisevolution',
            name='changes_in_family',
            field=models.TextField(blank=True, help_text='Descreva mudanças na composição familiar', verbose_name='Mudanças na família'),
        ),
        
        # Adicionar o campo changes_in_vulnerabilities
        migrations.AddField(
            model_name='socialanamnesisevolution',
            name='changes_in_vulnerabilities',
            field=models.TextField(blank=True, help_text='Descreva mudanças nas vulnerabilidades', verbose_name='Mudanças nas vulnerabilidades'),
        ),
        
        # Adicionar o campo changes_in_support_network
        migrations.AddField(
            model_name='socialanamnesisevolution',
            name='changes_in_support_network',
            field=models.TextField(blank=True, help_text='Descreva mudanças na rede de apoio', verbose_name='Mudanças na rede de apoio'),
        ),
        
        # Adicionar o campo attachments
        migrations.AddField(
            model_name='socialanamnesisevolution',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='social_anamnesis_evolutions/', verbose_name='Anexos'),
        ),
        
        # Adicionar o campo created_at
        migrations.AddField(
            model_name='socialanamnesisevolution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        
        # Remover campos antigos que não são mais necessários
        migrations.RemoveField(
            model_name='socialanamnesisevolution',
            name='date',
        ),
        migrations.RemoveField(
            model_name='socialanamnesisevolution',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='socialanamnesisevolution',
            name='evolution_type',
        ),
        migrations.RemoveField(
            model_name='socialanamnesisevolution',
            name='actions_taken',
        ),
        migrations.RemoveField(
            model_name='socialanamnesisevolution',
            name='next_steps',
        ),
    ]
