# Generated by Django 4.2.13 on 2025-07-15 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0011_update_socialanamnesisevolution_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['relationship', 'name'], 'verbose_name': 'Membro da Família', 'verbose_name_plural': 'Membros da Família'},
        ),
        migrations.AlterModelOptions(
            name='identifiedvulnerability',
            options={'ordering': ['-priority_date', '-created_at'], 'verbose_name': 'Vulnerabilidade Identificada', 'verbose_name_plural': 'Vulnerabilidades Identificadas'},
        ),
        migrations.AlterModelOptions(
            name='socialanamnesisevolution',
            options={'ordering': ['-evolution_date'], 'verbose_name': 'Evolução da Anamnese', 'verbose_name_plural': 'Evoluções da Anamnese'},
        ),
        migrations.AlterModelOptions(
            name='vulnerabilitycategory',
            options={'ordering': ['-priority_level', 'name'], 'verbose_name': 'Categoria de Vulnerabilidade', 'verbose_name_plural': 'Categorias de Vulnerabilidades'},
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='education',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='lives_together',
        ),
        migrations.RemoveField(
            model_name='identifiedvulnerability',
            name='intervention_description',
        ),
        migrations.AlterField(
            model_name='familymember',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='anamnesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='social.socialanamnesis'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda individual'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupação'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(choices=[('spouse', 'Cônjuge/Companheiro(a)'), ('child', 'Filho(a)'), ('parent', 'Pai/Mãe'), ('sibling', 'Irmão/Irmã'), ('grandparent', 'Avô/Avó'), ('grandchild', 'Neto(a)'), ('other', 'Outro')], max_length=20, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='identifiedvulnerability',
            name='anamnesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='social.socialanamnesis'),
        ),
        migrations.AlterField(
            model_name='identifiedvulnerability',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identified_vulnerabilities', to='social.vulnerabilitycategory'),
        ),
        migrations.AlterField(
            model_name='identifiedvulnerability',
            name='description',
            field=models.TextField(verbose_name='Descrição detalhada'),
        ),
        migrations.AlterField(
            model_name='identifiedvulnerability',
            name='intervention_needed',
            field=models.TextField(blank=True, help_text='Descreva que tipo de intervenção é necessária', verbose_name='Intervenção necessária'),
        ),
        migrations.AlterField(
            model_name='identifiedvulnerability',
            name='severity',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Gravidade'),
        ),
        migrations.AlterField(
            model_name='socialanamnesis',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_anamneses', to='members.beneficiary'),
        ),
        migrations.AlterField(
            model_name='socialanamnesis',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_social_anamnesis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialanamnesis',
            name='family_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda familiar'),
        ),
        migrations.AlterField(
            model_name='socialanamnesis',
            name='housing_situation',
            field=models.TextField(help_text='Descreva a situação habitacional da beneficiária', verbose_name='Situação habitacional'),
        ),
        migrations.AlterField(
            model_name='socialanamnesis',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Bloqueado para Edição'),
        ),
        migrations.AlterField(
            model_name='socialanamnesis',
            name='observations',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre a anamnese', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='socialanamnesis',
            name='signed_by_beneficiary',
            field=models.BooleanField(default=False, verbose_name='Assinado pela Beneficiária'),
        ),
        migrations.AlterField(
            model_name='socialanamnesis',
            name='signed_by_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='social_anamneses_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialanamnesis',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('completed', 'Concluída'), ('requires_update', 'Requer Atualização')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialanamnesis',
            name='support_network',
            field=models.TextField(help_text='Descreva a rede de apoio social da beneficiária', verbose_name='Rede de apoio'),
        ),
        migrations.AlterField(
            model_name='socialanamnesisevolution',
            name='anamnesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to='social.socialanamnesis'),
        ),
        migrations.AlterField(
            model_name='socialanamnesisevolution',
            name='description',
            field=models.TextField(verbose_name='Descrição da evolução'),
        ),
        migrations.AlterField(
            model_name='vulnerabilitycategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
