# Generated by Django 4.2.13 on 2025-07-11 15:57

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('dob', models.DateField(verbose_name='Data de Nascimento')),
                ('nis', models.CharField(blank=True, max_length=15, null=True, verbose_name='NIS')),
                ('phone_1', models.CharField(max_length=20, verbose_name='Telefone 1')),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2')),
                ('rg', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'))),
                ('cpf', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'))),
                ('address', models.TextField(verbose_name='Endereço')),
                ('neighbourhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('reference', models.TextField(blank=True, verbose_name='Ponto de Referência')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Beneficiária',
                'verbose_name_plural': 'Beneficiárias',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgpd_agreement', models.BooleanField(default=False, verbose_name='Concordo com LGPD')),
                ('image_use_agreement', models.BooleanField(default=False, verbose_name='Concordo com uso de imagem')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Assinado em')),
                ('signed_ip', models.GenericIPAddressField(verbose_name='IP da assinatura')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='consents/', verbose_name='PDF do Termo')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='members.beneficiary')),
            ],
            options={
                'verbose_name': 'Termo de Consentimento',
                'verbose_name_plural': 'Termos de Consentimento',
            },
        ),
    ]
