# Generated by Django 4.2.23 on 2025-06-16 16:45

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='cpf',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='rg',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
        ),
    ]
