# Generated by Django 4.2.23 on 2025-06-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_make_rg_cpf_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='status',
            field=models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=10, verbose_name='Status'),
        ),
    ]
