# Generated by Django 4.2.13 on 2025-07-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('html_message', models.TextField(blank=True, verbose_name='Mensagem HTML')),
                ('type', models.CharField(choices=[('welcome', 'Boas-vindas'), ('workshop_enrollment', 'Inscrição em Workshop'), ('workshop_reminder', 'Lembrete de Workshop'), ('certificate_ready', 'Certificado Pronto'), ('project_invitation', 'Convite para Projeto'), ('coaching_scheduled', 'Coaching Agendado'), ('system_update', 'Atualização do Sistema'), ('password_reset', 'Redefinição de Senha'), ('account_verification', 'Verificação de Conta'), ('general', 'Geral')], max_length=30, verbose_name='Tipo')),
                ('priority', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente')], default=1, verbose_name='Prioridade')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Lote')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendado'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='draft', max_length=20, verbose_name='Status')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Total de Destinatários')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Enviados')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Falharam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lote de Notificação',
                'verbose_name_plural': 'Lotes de Notificação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('display_name', models.CharField(max_length=100, verbose_name='Nome de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('configuration', models.JSONField(default=dict, verbose_name='Configuração')),
            ],
            options={
                'verbose_name': 'Canal de Notificação',
                'verbose_name_plural': 'Canais de Notificação',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='In-App')),
                ('workshop_notifications', models.BooleanField(default=True, verbose_name='Workshops')),
                ('certificate_notifications', models.BooleanField(default=True, verbose_name='Certificados')),
                ('project_notifications', models.BooleanField(default=True, verbose_name='Projetos')),
                ('coaching_notifications', models.BooleanField(default=True, verbose_name='Coaching')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='Sistema')),
                ('quiet_hours_start', models.TimeField(default='22:00', verbose_name='Início do Silêncio')),
                ('quiet_hours_end', models.TimeField(default='08:00', verbose_name='Fim do Silêncio')),
                ('frequency_limit', models.IntegerField(default=10, verbose_name='Limite de Notificações por Dia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificação',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('type', models.CharField(choices=[('welcome', 'Boas-vindas'), ('workshop_enrollment', 'Inscrição em Workshop'), ('workshop_reminder', 'Lembrete de Workshop'), ('certificate_ready', 'Certificado Pronto'), ('project_invitation', 'Convite para Projeto'), ('coaching_scheduled', 'Coaching Agendado'), ('system_update', 'Atualização do Sistema'), ('password_reset', 'Redefinição de Senha'), ('account_verification', 'Verificação de Conta'), ('general', 'Geral')], max_length=30, verbose_name='Tipo')),
                ('subject_template', models.CharField(help_text='Use variáveis como {{user.name}}, {{workshop.title}}', max_length=200, verbose_name='Template do Assunto')),
                ('content_template', models.TextField(help_text='Suporta HTML e variáveis', verbose_name='Template do Conteúdo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('priority', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente')], default=1, verbose_name='Prioridade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.notificationchannel', verbose_name='Canal')),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': 'Templates de Notificação',
            },
        ),
    ]
